# See: https://github.com/per1234/workflowsawaiting#configuration-file

- name: 107-systems
- name: aentinger/arduino-ci-status
- name: arduino
- name: Arduino-CI
- name: arduino-libraries
- name: snowfox-project
