# See: https://github.com/per1234/workflowsawaiting#configuration-file

- owner: 107-systems
- owner: arduino
- owner: arduino
  repo: docs-content
  action: ignore
- owner: Arduino-CI
- owner: arduino-libraries
