# See: https://github.com/per1234/workflowsawaiting#configuration-file

- owner: 107-systems
- owner: aentinger
  repo: arduino-ci-status
- owner: arduino
- owner: Arduino-CI
- owner: arduino-libraries
- owner: snowfox-project
